const cricketProducts = [
  {
    id: 1,
    title: "SG Nexus Xtreme English Willow Cricket Bat",
    author: "SG",
    price: 250,
    img: require("./assets/cricket/image1.jpg"),  
    amount: 1,
  },
  {
    id: 2,
    title: "GM Original Limited Edition Cricket Ball",
    author: "Gunn & Moore",
    price: 18,
    img: require("./assets/cricket/image2.jpg"),
    amount: 1,
  },
  {
    id: 3,
    title: "SS Master 5000 Cricket Helmet",
    author: "SS",
    price: 60,
    img: require("./assets/cricket/image3.jpg"),
    amount: 1,
  },
  {
    id: 4,
    title: "Kookaburra Kahuna Pro Cricket Bat",
    author: "Kookaburra",
    price: 280,
    img: require("./assets/cricket/image4.jpg"),
    amount: 1,
  },
  {
    id: 5,
    title: "Gray-Nicolls Legend Cricket Batting Gloves",
    author: "Gray-Nicolls",
    price: 45,
    img: require("./assets/cricket/image5.jpg"),
    amount: 1,
  },
  {
    id: 6,
    title: "Adidas Libro 2.0 Cricket Wheelie Bag",
    author: "Adidas",
    price: 80,
    img: require("./assets/cricket/image6.jpg"),
    amount: 1,
  },
  {
    id: 7,
    title: "New Balance CK10 Cricket Shoes",
    author: "New Balance",
    price: 70,
    img: require("./assets/cricket/image7.jpeg"),
    amount: 1,
  },
  {
    id: 8,
    title: "MRF Genius Grand Edition Cricket Bat",
    author: "MRF",
    price: 320,
    img: require("./assets/cricket/image8.jpg"),
    amount: 1,
  },
  {
    id: 9,
    title: "Puma evoSpeed Cricket Spike Shoes",
    author: "Puma",
    price: 55,
    img: require("./assets/cricket/image9.jpg"),
    amount: 1,
  },
  {
    id: 10,
    title: "Spartan MC 1000 Cricket Kit Bag",
    author: "Spartan",
    price: 40,
    img: require("./assets/cricket/image10.jpg"),
    amount: 1,
  },
  {
    id: 11,
    title: "SS Ton Professional English Willow Cricket Bat",
    author: "SS",
    price: 300,
    img: require("./assets/cricket/image11.jpg"),
    amount: 1,
  },
  {
    id: 12,
    title: "Gray-Nicolls Powerbow 6X Cricket Bag",
    author: "Gray-Nicolls",
    price: 50,
    img: require("./assets/cricket/image12.jpg"),
    amount: 1,
  },
];

export default cricketProducts;
