const footballProducts = [
  {
    id: 1,
    title: "Nike Premier Team FIFA Football",
    author: "Nike",
    price: 40,
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/df240bf6-774a-402c-9a58-e9fb95f95a09/premier-team-football-sZzRHW.png",
    amount: 1,
  },
  {
    id: 2,
    title: "Adidas Tango All-around Training Football",
    author: "Adidas",
    price: 30,
    img: "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/e0000c573e0a48eb9c97ab6d0123788b_9366/Tango_All_Around_Ball_White_EH8505_01_standard.jpg",
    amount: 1,
  },
  {
    id: 3,
    title: "Puma Future 5.4 FG/AG Football Boots",
    author: "Puma",
    price: 60,
    img: "https://images-na.ssl-images-amazon.com/images/I/61T6plcpaPL._AC_UY625_.jpg",
    amount: 1,
  },
  {
    id: 4,
    title: "Under Armour Desafio 395 Soccer Ball",
    author: "Under Armour",
    price: 25,
    img: "https://cdn.shopify.com/s/files/1/2426/7107/products/Desafio395_2_2048x.jpg?v=1581061063",
    amount: 1,
  },
  {
    id: 5,
    title: "New Balance Furon v6 Pro FG Football Boots",
    author: "New Balance",
    price: 120,
    img: "https://i.ebayimg.com/images/g/aC4AAOSw1Xdd6kUK/s-l1600.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "Uhlsport Eliminator Soft Graphit Goalkeeper Gloves",
    author: "Uhlsport",
    price: 35,
    img: "https://www.keeper-id.com/wp-content/uploads/2019/09/ElGrap1.png",
    amount: 1,
  },
  {
    id: 7,
    title: "Mitre Ultimatch Hyperseam Match Football",
    author: "Mitre",
    price: 22,
    img: "https://www.3qsports.co.uk/wp-content/uploads/2018/06/Ultimatch-Match-Ball-Football-White.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "Kwik Goal Infinity Pop-Up Soccer Goal",
    author: "Kwik Goal",
    price: 50,
    img: "https://www.soccersavings.com/dw/image/v2/AAJD_PRD/on/demandware.static/-/Sites-master-product-catalog/default/dw4d15c27e/images/large/20190816_kwik_goal_infinity_pop_up_soccer_goal_set.jpg?sw=1500&sh=1500&sm=fit",
    amount: 1,
  },
  {
    id: 9,
    title: "Select Numero 10 Soccer Ball",
    author: "Select",
    price: 50,
    img: "https://www.select-sport.com/image/cache/catalog/num10-500x500.jpg",
    amount: 1,
  },
  {
    id: 10,
    title: "Copa Zone Cushion II Soccer Socks",
    author: "Adidas",
    price: 12,
    img: "https://images-na.ssl-images-amazon.com/images/I/71tljTjyJgL._AC_UX425_.jpg",
    amount: 1,
  },
  {
    id: 11,
    title: "SKLZ Star-Kick Hands-Free Solo Soccer Trainer",
    author: "SKLZ",
    price: 15,
    img: "https://m.media-amazon.com/images/I/61jYlYkRnsL._AC_UY500_.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "Nike Mercurial Lite Soccer Shin Guards",
    author: "Nike",
    price: 25,
    img: "https://static.nike.com/a/images/c_limit,w_318,f_auto/t_product_v1/i1-7f9cb33b-3b1f-4b57-805c-1aa5a7b1ef0e/mercurial-lite-football-shin-guards-FlZxP2.png",
    amount: 1,
  },
];

export default footballProducts;
